"""Add user name to webhooks, remove last activity from chatrooms

Revision ID: 50f1b4afef36
Revises: 581d8f7f3805
Create Date: 2026-01-14 10:50:39.451420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f1b4afef36'
down_revision: Union[str, Sequence[str], None] = '581d8f7f3805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatrooms', 'last_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatrooms', sa.Column('last_activity', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
