"""Initial migration: chatrooms, messages, facilitation_logs

Revision ID: 581d8f7f3805
Revises: 
Create Date: 2026-01-11 13:18:36.408350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581d8f7f3805'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatrooms_external_id'), 'chatrooms', ['external_id'], unique=True)
    op.create_index(op.f('ix_chatrooms_id'), 'chatrooms', ['id'], unique=False)
    op.create_table('facilitation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatroom_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('stage1_result', sa.JSON(), nullable=True),
    sa.Column('stage2_result', sa.JSON(), nullable=True),
    sa.Column('stage3_result', sa.JSON(), nullable=True),
    sa.Column('final_decision', sa.Enum('NO_FACILITATION', 'NO_FACILITATION_AFTER_VERIFY', 'FACILITATE', name='facilitationdecision'), nullable=False),
    sa.Column('facilitation_message', sa.Text(), nullable=True),
    sa.Column('message_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilitation_logs_chatroom_id'), 'facilitation_logs', ['chatroom_id'], unique=False)
    op.create_index(op.f('ix_facilitation_logs_id'), 'facilitation_logs', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatroom_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chatroom_id'), 'messages', ['chatroom_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chatroom_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_facilitation_logs_id'), table_name='facilitation_logs')
    op.drop_index(op.f('ix_facilitation_logs_chatroom_id'), table_name='facilitation_logs')
    op.drop_table('facilitation_logs')
    op.drop_index(op.f('ix_chatrooms_id'), table_name='chatrooms')
    op.drop_index(op.f('ix_chatrooms_external_id'), table_name='chatrooms')
    op.drop_table('chatrooms')
    # ### end Alembic commands ###
