"""add is active to chatrooms

Revision ID: 7206d0b41c43
Revises: de11aa7c5217
Create Date: 2026-01-22 22:43:21.172311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7206d0b41c43'
down_revision: Union[str, Sequence[str], None] = 'de11aa7c5217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatrooms', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatrooms', 'is_active')
    # ### end Alembic commands ###
