"""initial_schema

Revision ID: 89565fea5039
Revises:
Create Date: 2026-03-16 10:34:31.887694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89565fea5039"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Integer(), nullable=False),
        sa.Column("group_name", sa.String(length=256), nullable=False),
        sa.Column("last_ai_message_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_groups_external_id"), "groups", ["external_id"], unique=True
    )
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_external_id"), "questions", ["external_id"], unique=True
    )
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_user_id", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=256), nullable=False),
        sa.Column("last_name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_external_user_id"), "users", ["external_user_id"], unique=True
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "group_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("unlock_order", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "question_id", name="uq_group_question"),
    )
    op.create_index(
        op.f("ix_group_questions_group_id"),
        "group_questions",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_questions_id"), "group_questions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_group_questions_question_id"),
        "group_questions",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "user_id", name="uq_group_user"),
    )
    op.create_index(op.f("ix_members_group_id"), "members", ["group_id"], unique=False)
    op.create_index(op.f("ix_members_id"), "members", ["id"], unique=False)
    op.create_index(op.f("ix_members_user_id"), "members", ["user_id"], unique=False)
    op.create_table(
        "question_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_options_id"), "question_options", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_question_options_question_id"),
        "question_options",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "facilitation_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("group_question_id", sa.Integer(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(), nullable=False),
        sa.Column("stage1_result", sa.JSON(), nullable=True),
        sa.Column("stage2_result", sa.JSON(), nullable=True),
        sa.Column("stage3_result", sa.JSON(), nullable=True),
        sa.Column(
            "final_decision",
            sa.Enum(
                "NO_FACILITATION",
                "NO_FACILITATION_AFTER_VERIFY",
                "FACILITATE",
                name="facilitationdecision",
            ),
            nullable=False,
        ),
        sa.Column("facilitation_message", sa.Text(), nullable=True),
        sa.Column("message_sent_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_question_id"],
            ["group_questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_facilitation_logs_group_id"),
        "facilitation_logs",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facilitation_logs_group_question_id"),
        "facilitation_logs",
        ["group_question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facilitation_logs_id"), "facilitation_logs", ["id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("group_question_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("is_ai", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_question_id"],
            ["group_questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_group_id"), "messages", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_group_question_id"),
        "messages",
        ["group_question_id"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_group_question_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_group_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_facilitation_logs_id"), table_name="facilitation_logs")
    op.drop_index(
        op.f("ix_facilitation_logs_group_question_id"), table_name="facilitation_logs"
    )
    op.drop_index(op.f("ix_facilitation_logs_group_id"), table_name="facilitation_logs")
    op.drop_table("facilitation_logs")
    op.drop_index(
        op.f("ix_question_options_question_id"), table_name="question_options"
    )
    op.drop_index(op.f("ix_question_options_id"), table_name="question_options")
    op.drop_table("question_options")
    op.drop_index(op.f("ix_members_user_id"), table_name="members")
    op.drop_index(op.f("ix_members_id"), table_name="members")
    op.drop_index(op.f("ix_members_group_id"), table_name="members")
    op.drop_table("members")
    op.drop_index(op.f("ix_group_questions_question_id"), table_name="group_questions")
    op.drop_index(op.f("ix_group_questions_id"), table_name="group_questions")
    op.drop_index(op.f("ix_group_questions_group_id"), table_name="group_questions")
    op.drop_table("group_questions")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_external_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_external_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_external_id"), table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
