"""
Pydantic schemas for request/response validation.
Used by FastAPI for automatic validation and serialization.
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, ConfigDict

from app.models.database import FacilitationDecision


# ===== Webhook Schemas =====
class WebhookIncomingGroupMetadata(BaseModel):
    group_id: int = Field(..., alias="group_id")
    status: str = Field(..., alias="status")

class WebhookIncomingGroupsMetadata(BaseModel):
    groups_metadata: List[WebhookIncomingGroupMetadata] = Field(..., alias="groups_metadata")

class WebhookIncomingGroupMember(BaseModel):
    user_id: str = Field(
        ..., alias="user_id", description="User UUID from external system"
    )
    first_name: str = Field(
        ..., alias="first_name", description="First name of the user"
    )
    last_name: Optional[str] = Field(
        "", alias="last_name", description="Last name of the user"
    )

    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "example": {
                "user_id": "uuid-user-1",
                "first_name": "John",
                "last_name": "Doe",
            }
        },
    )


class WebhookIncomingQuestion(BaseModel):
    id: str = Field(..., description="Question ID from external system")
    text: str = Field(..., description="Question text")
    options: List[str] = Field(..., description="List of possible answer categories")
    status: str = Field(..., description="Status of the question (active, inactive)")
    unlock_order: int = Field(
        ..., alias="unlock_order", description="Order in which the question is unlocked"
    )

    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "example": {
                "id": "uuid-question-1",
                "text": "What's your favorite childhood memory?",
                "options": ["Family vacations", "School events", "Holidays", "Other"],
                "status": "active",
                "unlock_order": 1,
            }
        },
    )


class WebhookIncomingMessage(BaseModel):
    question_id: str = Field(
        ...,
        alias="question_id",
        description="Question ID associated with the message (optional)",
    )
    user_id: str = Field(
        ..., alias="user_id", description="User UUID who sent the message"
    )
    first_name: str = Field(
        ...,
        alias="first_name",
        description="First name of the user who sent the message",
    )
    last_name: Optional[str] = Field(
        "", alias="last_name", description="Last name of the user who sent the message"
    )
    content: str = Field(..., description="Message content")
    created_at: datetime = Field(
        ...,
        alias="created_at",
        description="Timestamp when message was created YYYY-MM-DDTHH:MM:SSZ format",
    )
    is_ai: bool = Field(
        ..., alias="is_ai", description="Indicates if the message was generated by AI"
    )

    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "example": {
                "question_id": "uuid-question-1",
                "user_id": "uuid-user-1",
                "first_name": "John",
                "last_name": "Doe",
                "content": "<highlight>Family vacations</highlight> I loved our summer camping trips!",
                "created_at": "2024-01-14T10:30:00Z",
                "is_ai": False,
            }
        },
    )


class WebhookIncomingGroup(BaseModel):
    group_id: int = Field(
        ..., alias="group_id", description="Chatroom ID from external system"
    )
    group_name: str = Field(
        ..., alias="group_name", description="Chatroom name from external system"
    )
    members: List[WebhookIncomingGroupMember] = Field(
        ..., description="List of members in the group"
    )
    questions: List[WebhookIncomingQuestion] = Field(
        ..., description="List of questions associated with the group"
    )
    messages: List[WebhookIncomingMessage] = Field(
        ..., description="List of new messages sent in the group"
    )
    last_ai_message_at: Optional[datetime] = Field(
        None,
        alias="last_ai_message_at",
        description="Timestamp of the last AI message sent",
    )

    model_config = ConfigDict(populate_by_name=True)


class WebhookIncomingRequest(BaseModel):
    groups: List[WebhookIncomingGroup] = Field(
        ..., description="List of groups in the incoming webhook payload"
    )
    model_config = ConfigDict(
        populate_by_name=True, json_schema_extra={"example": {"groups": []}}
    )


class FacilitationMessageResponse(BaseModel):
    """Outgoing facilitation message response."""

    group_id: int = Field(..., description="Chatroom UUID")
    question_id: str = Field(..., description="Question UUID we are replying within")
    message: str = Field(..., description="Generated facilitation message")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "group_id": 123,
                "question_id": "uuid-question-1",
                "message": "It sounds like everyone is going through similar challenges...",
            }
        }
    )


class FacilitationBatchMessagesResponse(BaseModel):
    """Outgoing batch facilitation messages response."""

    facilitation_responses: List[FacilitationMessageResponse] = Field(
        ..., description="List of facilitation messages for chatrooms"
    )

    model_config = ConfigDict(populate_by_name=True)


class WebhookResponse(BaseModel):
    """Response for webhook endpoint after storing messages."""

    status: str = "success"
    messages_received: int = Field(..., description="Number of messages received")
    groups_affected: int = Field(..., description="Number of groups affected")
    question_threads_affected: int = Field(
        ..., description="Number of question threads modified"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "status": "success",
                "messages_received": 5,
                "groups_affected": 2,
                "question_threads_affected": 3,
            }
        }
    )


# ===== Group Schemas =====


class GroupBase(BaseModel):
    """Base Group schema."""

    external_id: int
    group_name: str = ""


class GroupCreate(GroupBase):
    """Schema for creating a new group."""

    pass


class GroupResponse(GroupBase):
    """Schema for group response."""

    id: int
    created_at: datetime
    model_config = ConfigDict(from_attributes=True)


class GroupUpdateRequest(BaseModel):
    """Schema for updating group metadata."""

    group_id: int = Field(..., description="External group ID to update")
    is_active: bool = Field(..., description="Active status of the group")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "group_id": 123,
                "is_active": False,
            }
        }
    )


class GroupUpdateResponse(BaseModel):
    """Schema for group update response."""

    status: str = "success"
    group_id: int = Field(..., description="External group ID that was updated")
    is_active: bool = Field(..., description="New active status")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "status": "success",
                "group_id": 123,
                "is_active": False,
            }
        }
    )


# ===== Message Schemas =====


class MessageBase(BaseModel):
    """Base message schema."""

    content: str
    timestamp: datetime
    is_ai: bool = False


class MessageCreate(MessageBase):
    """Schema for creating a new message."""

    group_id: int
    user_id: int
    group_question_id: int


class MessageResponse(MessageBase):
    """Schema for message response."""

    id: int
    group_id: int
    user_id: int
    group_question_id: int
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


# ===== Facilitation Log Schemas =====


class FacilitationLogBase(BaseModel):
    """Base facilitation log schema."""

    final_decision: FacilitationDecision
    facilitation_message: Optional[str] = None


class FacilitationLogCreate(FacilitationLogBase):
    """Schema for creating facilitation log."""

    group_id: int
    group_question_id: int
    stage1_result: Optional[dict] = None
    stage2_result: Optional[dict] = None
    stage3_result: Optional[dict] = None
    message_sent_at: Optional[datetime] = None


class FacilitationLogResponse(FacilitationLogBase):
    """Schema for facilitation log response."""

    id: int
    group_id: int
    group_question_id: int
    triggered_at: datetime
    stage1_result: Optional[dict] = None
    stage2_result: Optional[dict] = None
    stage3_result: Optional[dict] = None
    message_sent_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


# ===== API Response Schemas =====


class HealthCheckResponse(BaseModel):
    """Health check endpoint response."""

    status: str = "healthy"
    timestamp: datetime = Field(default_factory=datetime.now())
    version: str = "1.0.0"


class ConversationHistoryResponse(BaseModel):
    """Conversation history response."""

    chatroom_id: int
    messages: List[MessageResponse]
    total_messages: int


class FacilitationCheckRequest(BaseModel):
    """Manual facilitation check request."""

    group_id: int = Field(..., description="Chatroom UUID to check")

    model_config = ConfigDict(json_schema_extra={"example": {"group_id": 123}})


class FacilitationCheckResponse(BaseModel):
    """Facilitation check response."""

    group_id: str
    decision: FacilitationDecision
    message: Optional[str] = None
    log_id: int
