"""
Pydantic schemas for request/response validation.
Used by FastAPI for automatic validation and serialization.
"""

from datetime import datetime
from typing import Any, Optional, List
import re
from pydantic import BaseModel, Field, ConfigDict, field_validator

from app.models.database import FacilitationDecision


# ===== Webhook Schemas =====
class WebhookIncomingGroupMetadata(BaseModel):
    group_id: int
    status: str
    status_updated_at: Optional[datetime] = None


class WebhookIncomingGroupMember(BaseModel):
    user_id: str = Field(..., description="User UUID from external system")
    first_name: Optional[str] = Field(None, description="First name of the user")
    last_name: Optional[str] = Field(None, description="Last name of the user")

    model_config = ConfigDict(populate_by_name=True)


class WebhookIncomingQuestion(BaseModel):
    id: str = Field(..., description="Question ID from external system")
    text: str = Field(..., description="Question text")
    options: List[str] = Field(..., description="List of possible answer categories")
    status: str = Field(
        ..., description="Status of the question (active, expired, pending)"
    )
    unlock_order: int = Field(
        ..., description="Order in which the question is unlocked"
    )

    model_config = ConfigDict(populate_by_name=True)


class WebhookIncomingMessage(BaseModel):
    user_id: str = Field(..., description="User UUID who sent the message")
    first_name: Optional[str] = Field(None, description="First name of the sender")
    last_name: Optional[str] = Field(None, description="Last name of the sender")
    content: str = Field(..., description="Message content")
    created_at: datetime = Field(..., description="Timestamp when message was created")
    is_ai: bool = Field(..., description="Indicates if the message was generated by AI")
    is_current_member: bool = Field(
        True, description="Whether sender is a current group member"
    )

    @field_validator("created_at", mode="before")
    @classmethod
    def normalize_timezone(cls, v: Any) -> Any:
        """Normalize short timezone offsets like +00 or -05 to +00:00 / -05:00."""
        if isinstance(v, str):
            v = re.sub(r"([+-]\d{2})$", r"\1:00", v)
        return v

    model_config = ConfigDict(populate_by_name=True)


class WebhookIncomingThread(BaseModel):
    question: WebhookIncomingQuestion
    messages: List[WebhookIncomingMessage]
    last_ai_message_at: Optional[datetime] = None

    model_config = ConfigDict(populate_by_name=True)


class WebhookIncomingGroup(BaseModel):
    group_id: int = Field(..., description="Chatroom ID from external system")
    group_name: str = Field(..., description="Chatroom name from external system")
    members: List[WebhookIncomingGroupMember] = Field(
        ..., description="List of members in the group"
    )
    threads: List[WebhookIncomingThread] = Field(
        ..., description="List of question threads in the group"
    )

    model_config = ConfigDict(populate_by_name=True)


class WebhookIncomingPayload(BaseModel):
    groups_metadata: List[WebhookIncomingGroupMetadata] = Field(
        ..., description="Metadata for all groups including status"
    )
    groups: List[WebhookIncomingGroup] = Field(
        ..., description="Full group data with threads and messages"
    )

    model_config = ConfigDict(populate_by_name=True)


class WebhookIncomingRequest(BaseModel):
    payload: WebhookIncomingPayload

    model_config = ConfigDict(populate_by_name=True)


class FacilitationMessageResponse(BaseModel):
    """Outgoing facilitation message response."""

    group_id: int = Field(..., description="Chatroom UUID")
    question_id: str = Field(..., description="Question UUID we are replying within")
    content: str = Field(..., description="Generated facilitation message")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "group_id": 123,
                "question_id": "uuid-question-1",
                "content": "It sounds like everyone is going through similar challenges...",
            }
        }
    )


class FacilitationBatchMessagesResponse(BaseModel):
    """Outgoing batch facilitation messages response."""

    facilitation_responses: List[FacilitationMessageResponse] = Field(
        ..., description="List of facilitation messages for chatrooms"
    )

    model_config = ConfigDict(populate_by_name=True)


class WebhookResponse(BaseModel):
    """Response for webhook endpoint after storing messages."""

    status: str = "success"
    messages_received: int = Field(..., description="Number of messages received")
    groups_affected: int = Field(..., description="Number of groups affected")
    question_threads_affected: int = Field(
        ..., description="Number of question threads modified"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "status": "success",
                "messages_received": 5,
                "groups_affected": 2,
                "question_threads_affected": 3,
            }
        }
    )


# ===== Group Schemas =====


class GroupBase(BaseModel):
    """Base Group schema."""

    external_id: int
    group_name: str = ""


class GroupCreate(GroupBase):
    """Schema for creating a new group."""

    pass


class GroupResponse(GroupBase):
    """Schema for group response."""

    id: int
    created_at: datetime
    model_config = ConfigDict(from_attributes=True)


class GroupUpdateRequest(BaseModel):
    """Schema for updating group metadata."""

    group_id: int = Field(..., description="External group ID to update")
    is_active: bool = Field(..., description="Active status of the group")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "group_id": 123,
                "is_active": False,
            }
        }
    )


class GroupUpdateResponse(BaseModel):
    """Schema for group update response."""

    status: str = "success"
    group_id: int = Field(..., description="External group ID that was updated")
    is_active: bool = Field(..., description="New active status")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "status": "success",
                "group_id": 123,
                "is_active": False,
            }
        }
    )


# ===== Message Schemas =====


class MessageBase(BaseModel):
    """Base message schema."""

    content: str
    timestamp: datetime
    is_ai: bool = False


class MessageCreate(MessageBase):
    """Schema for creating a new message."""

    group_id: int
    user_id: int
    group_question_id: int


class MessageResponse(MessageBase):
    """Schema for message response."""

    id: int
    group_id: int
    user_id: int
    group_question_id: int
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


# ===== Facilitation Log Schemas =====


class FacilitationLogBase(BaseModel):
    """Base facilitation log schema."""

    final_decision: FacilitationDecision
    facilitation_message: Optional[str] = None


class FacilitationLogCreate(FacilitationLogBase):
    """Schema for creating facilitation log."""

    group_id: int
    group_question_id: int
    stage1_result: Optional[dict] = None
    stage2_result: Optional[dict] = None
    stage3_result: Optional[dict] = None
    message_sent_at: Optional[datetime] = None


class FacilitationLogResponse(FacilitationLogBase):
    """Schema for facilitation log response."""

    id: int
    group_id: int
    group_question_id: int
    triggered_at: datetime
    stage1_result: Optional[dict] = None
    stage2_result: Optional[dict] = None
    stage3_result: Optional[dict] = None
    message_sent_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


# ===== API Response Schemas =====


class HealthCheckResponse(BaseModel):
    """Health check endpoint response."""

    status: str = "healthy"
    timestamp: datetime = Field(default_factory=datetime.now())
    version: str = "1.0.0"


class ConversationHistoryResponse(BaseModel):
    """Conversation history response."""

    chatroom_id: int
    messages: List[MessageResponse]
    total_messages: int


class FacilitationCheckRequest(BaseModel):
    """Manual facilitation check request."""

    group_id: int = Field(..., description="Chatroom UUID to check")

    model_config = ConfigDict(json_schema_extra={"example": {"group_id": 123}})


class FacilitationCheckResponse(BaseModel):
    """Facilitation check response."""

    group_id: str
    decision: FacilitationDecision
    message: Optional[str] = None
    log_id: int
