"""
Pydantic schemas for request/response validation.
Used by FastAPI for automatic validation and serialization.
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, ConfigDict

from app.models.database import FacilitationDecision


# ===== Webhook Schemas =====
class WebhookIncomingGroupMember(BaseModel):
    user_id: str = Field(..., alias="userId", description="User UUID from external system")
    first_name: str = Field(..., alias="firstName", description="First name of the user")
    last_name: str = Field(..., alias="lastName", description="Last name of the user")

    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "example": {"userId": "uuid-user-1", "firstName": "John", "lastName": "Doe"}
        }
    )


class WebhookIncomingQuestion(BaseModel):
    id: str = Field(..., description="Question ID from external system")
    text: str = Field(..., description="Question text")
    options: List[str] = Field(..., description="List of possible answer categories")
    status: str = Field(..., description="Status of the question (active, inactive)")
    unlock_order: int = Field(
        ..., alias="unlockOrder", description="Order in which the question is unlocked"
    )

    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "example": {
                "id": "uuid-question-1",
                "text": "What's your favorite childhood memory?",
                "options": ["Family vacations", "School events", "Holidays", "Other"],
                "status": "active",
                "unlockOrder": 1,
            }
        }
    )


class WebhookIncomingMessage(BaseModel):
    question_id: str = Field(..., alias="questionId", description="Question ID associated with the message")
    user_id: str = Field(..., alias="userId", description="User UUID who sent the message")
    first_name: str = Field(
        ..., alias="firstName", description="First name of the user who sent the message"
    )
    last_name: str = Field(
        ..., alias="lastName", description="Last name of the user who sent the message"
    )
    content: str = Field(..., description="Message content")
    created_at: datetime = Field(
        ...,
        alias="createdAt",
        description="Timestamp when message was created YYYY-MM-DDTHH:MM:SSZ format",
    )
    is_ai: bool = Field(..., alias="isAi", description="Indicates if the message was generated by AI")

    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "example": {
                "questionId": "uuid-question-1",
                "userId": "uuid-user-1",
                "firstName": "John",
                "lastName": "Doe",
                "content": "<highlight>Family vacations</highlight> I loved our summer camping trips!",
                "createdAt": "2024-01-14T10:30:00Z",
                "isAi": False,
            }
        }
    )


class WebhookIncomingGroup(BaseModel):
    group_id: int = Field(..., alias="groupId", description="Chatroom ID from external system")
    group_name: str = Field(..., alias="groupName", description="Chatroom name from external system")
    members: List[WebhookIncomingGroupMember] = Field(
        ..., description="List of members in the group"
    )
    questions: List[WebhookIncomingQuestion] = Field(
        ..., description="List of questions associated with the group"
    )
    messages: List[WebhookIncomingMessage] = Field(
        ..., description="List of new messages sent in the group"
    )
    last_ai_message_at: Optional[datetime] = Field(
        None, alias="lastAiMessageAt", description="Timestamp of the last AI message sent"
    )

    model_config = ConfigDict(populate_by_name=True)


class WebhookIncomingRequest(BaseModel):
    groups: List[WebhookIncomingGroup] = Field(
        ..., description="List of groups in the incoming webhook payload"
    )
    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={"example": {"groups": []}}
    )


class FacilitationMessageResponse(BaseModel):
    """Outgoing facilitation message response."""

    group_id: int = Field(..., description="Chatroom UUID")
    message: str = Field(..., description="Generated facilitation message")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "group_id": 123,
                "message": "It sounds like everyone is going through similar challenges...",
            }
        }
    )


class FacilitationBatchMessagesResponse(BaseModel):
    """Outgoing batch facilitation messages response."""

    facilitation_responses: List[FacilitationMessageResponse] = Field(
        ..., description="List of facilitation messages for chatrooms"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "facilitation_responses": [
                    {
                        "group_id": 123,
                        "message": "It sounds like everyone is going through similar challenges...",
                    },
                    {
                        "group_id": 456,
                        "message": "Remember to take breaks and support each other!",
                    },
                ]
            }
        }
    )


class WebhookResponse(BaseModel):
    """Response for webhook endpoint after storing messages."""

    status: str = "success"
    messages_received: int = Field(..., description="Number of messages received")
    chatrooms_affected: int = Field(..., description="Number of chatrooms affected")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "status": "success",
                "messages_received": 5,
                "chatrooms_affected": 2,
            }
        }
    )


# ===== Chatroom Schemas =====


class ChatroomBase(BaseModel):
    """Base chatroom schema."""

    external_id: int
    is_active: bool = True


class ChatroomCreate(ChatroomBase):
    """Schema for creating a new chatroom."""

    pass


class ChatroomResponse(ChatroomBase):
    """Schema for chatroom response."""

    id: int
    created_at: datetime
    model_config = ConfigDict(from_attributes=True)


# ===== Message Schemas =====


class MessageBase(BaseModel):
    """Base message schema."""

    sender_id: str
    sender_name: str
    content: str
    timestamp: datetime


class MessageCreate(MessageBase):
    """Schema for creating a new message."""

    chatroom_id: int


class MessageResponse(MessageBase):
    """Schema for message response."""

    id: int
    chatroom_id: int
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


# ===== Facilitation Log Schemas =====


class FacilitationLogBase(BaseModel):
    """Base facilitation log schema."""

    final_decision: FacilitationDecision
    facilitation_message: Optional[str] = None


class FacilitationLogCreate(FacilitationLogBase):
    """Schema for creating facilitation log."""

    chatroom_id: int
    stage1_result: Optional[dict] = None
    stage2_result: Optional[dict] = None
    stage3_result: Optional[dict] = None
    message_sent_at: Optional[datetime] = None


class FacilitationLogResponse(FacilitationLogBase):
    """Schema for facilitation log response."""

    id: int
    chatroom_id: int
    triggered_at: datetime
    stage1_result: Optional[dict] = None
    stage2_result: Optional[dict] = None
    stage3_result: Optional[dict] = None
    message_sent_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


# ===== API Response Schemas =====


class HealthCheckResponse(BaseModel):
    """Health check endpoint response."""

    status: str = "healthy"
    timestamp: datetime = Field(default_factory=datetime.now())
    version: str = "1.0.0"


class ConversationHistoryResponse(BaseModel):
    """Conversation history response."""

    chatroom_id: int
    messages: List[MessageResponse]
    total_messages: int


class FacilitationCheckRequest(BaseModel):
    """Manual facilitation check request."""

    group_id: int = Field(..., description="Chatroom UUID to check")

    model_config = ConfigDict(json_schema_extra={"example": {"group_id": 123}})


class FacilitationCheckResponse(BaseModel):
    """Facilitation check response."""

    group_id: str
    decision: FacilitationDecision
    message: Optional[str] = None
    log_id: int
